# AGORA PARA VERIFICAR E TESTAR O GRAFICO DE DISPERSAO, VAMOS FAZER UMA ANALISE DE QUE AUMENTANDO A MEDIA DE RENDA AUMENTA-SE O VALOR DAS CASAS
# CONCLUI-SE COM O GRAFICO DE DISPERSAO QUE QUANTO MAIS OS VALORES DE RENDA AUMENTAM, AUMENTAM OS VALORES DAS CASAS


https://colab.research.google.com/drive/1wqUZyVogLcz4fwD2cEhkGYUiIZaMu6rR#scrollTo=_InQpUhBYMgE


df.plot.scatter(x='median_income',y='median_house_value',s=0.1)
plt.show()
